from __future__ import annotations

import argparse
from pathlib import Path


DOC_TEMPLATES = {
  '00-intake.md': 'intake.template.md',
  '01-prd-draft.md': 'prd-draft.template.md',
  '02-ux-spec.md': 'ux-spec.template.md',
  '03-prd-final.md': 'prd-final.template.md',
  '04-architecture.md': 'add.template.md',
  '05-dev-plan.md': 'dev-plan.template.md',
  '06-test-cases.md': 'test-cases.template.md',
  '07-test-report.md': 'test-report.template.md',
  '08-release-gate.md': 'release-gate.template.md',
  '09-retro-input.md': 'retro-input.template.md',
}


def slug_to_package_name(product_slug: str) -> str:
  return product_slug.replace('-', '_')


def populate_common_fields(template: str, app_name: str, product_slug: str) -> str:
  replacements = {
    '## Project Name\n': f'## Project Name\n{app_name}\n',
    '## Project Slug\n': f'## Project Slug\n{product_slug}\n',
  }
  content = template
  for marker, value in replacements.items():
    content = content.replace(marker, value)
  return content


def write_text(path: Path, content: str) -> None:
  path.parent.mkdir(parents=True, exist_ok=True)
  path.write_text(content, encoding='utf-8')


def copy_doc_templates(repo_root: Path, product_root: Path, app_name: str, product_slug: str) -> None:
  template_root = repo_root / 'templates/docs'
  docs_root = product_root / 'docs'
  docs_root.mkdir(parents=True, exist_ok=True)

  for target_name, template_name in DOC_TEMPLATES.items():
    template = (template_root / template_name).read_text(encoding='utf-8')
    content = populate_common_fields(template, app_name, product_slug)
    write_text(docs_root / target_name, content)

  figma_template = (template_root / 'figma-link.template.md').read_text(encoding='utf-8')
  figma_content = populate_common_fields(figma_template, app_name, product_slug)
  write_text(product_root / 'design/figma-link.md', figma_content)
  write_text(product_root / 'design/exports/.gitkeep', '')


def build_pubspec(app_name: str, product_slug: str) -> str:
  package_name = slug_to_package_name(product_slug)
  return f"""name: {package_name}
description: {app_name} product shell generated by AppFactory.
publish_to: none
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  app_factory_account:
    path: ../../packages/app_factory_account
  app_factory_foundation:
    path: ../../packages/app_factory_foundation
  app_factory_growth:
    path: ../../packages/app_factory_growth
  app_factory_ui:
    path: ../../packages/app_factory_ui
  app_factory_tooling:
    path: ../../packages/app_factory_tooling

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
"""


def build_app_config(product_slug: str) -> str:
  return f"""name: {product_slug}
platforms:
  - ios
  - android
  - web
output_dir: build/outputs
server_mode: reserved
upgrade:
  check_on_launch: true
  soft_update_window: 3
  current_version: 0.1.0
  current_build_number: 1
  latest_version: 0.1.0
  latest_build_number: 1
"""


def build_server_readme(app_name: str) -> str:
  return f"""# Server Boundary

{app_name} reserves a product-local `server/` boundary for future backend logic.

## Default Rule

- Shared account, payment, subscription, and entitlement services should be reused from shared services when possible.
- Product-specific server logic should be added only when PM and AM decide the product needs dedicated backend behavior.
- Until then, this directory remains a reserved boundary and deployment placeholder.
"""


def build_server_config(product_slug: str) -> str:
  return f"""name: {product_slug}
mode: reserved
shared_account_service: preferred
shared_payment_service: preferred
"""


def build_bootstrap(app_name: str) -> str:
  return f"""import 'package:app_factory_foundation/app_factory_foundation.dart';
import 'package:app_factory_growth/app_factory_growth.dart';

class AppServices {{
  const AppServices({{
    required this.config,
    required this.registry,
    required this.upgradeDecision,
  }});

  final AppConfig config;
  final CapabilityRegistry registry;
  final UpgradeDecision upgradeDecision;
}}

Future<AppServices> bootstrapApp() async {{
  final CapabilityRegistry registry = CapabilityRegistry();
  const GrowthEntryPoints growthEntryPoints = GrowthEntryPoints();
  registry.register<AppLogger>(AppLogger());
  registry.register<ErrorReporter>(ErrorReporter());
  registry.register<GrowthEntryPoints>(growthEntryPoints);

  const AppConfig config = AppConfig(
    appName: '{app_name}',
    currentVersion: '0.1.0',
    currentBuildNumber: 1,
    latestVersion: '0.1.0',
    latestBuildNumber: 1,
  );
  final UpgradeDecision upgradeDecision = growthEntryPoints.upgradePolicy.evaluate(
    currentVersion: config.currentVersion,
    currentBuildNumber: config.currentBuildNumber,
    latestVersion: config.latestVersion,
    latestBuildNumber: config.latestBuildNumber,
    upgradeUrl: config.upgradeUrl,
  );
  registry.register<UpgradeDecision>(upgradeDecision);

  return AppServices(
    config: config,
    registry: registry,
    upgradeDecision: upgradeDecision,
  );
}}
"""


def build_app(package_name: str, class_name: str, home_title: str) -> str:
  return f"""import 'package:app_factory_growth/app_factory_growth.dart';
import 'package:app_factory_ui/app_factory_ui.dart';
import 'package:{package_name}/app/bootstrap.dart';
import 'package:{package_name}/features/home/home_page.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

class {class_name} extends StatelessWidget {{
  const {class_name}({{
    super.key,
    required this.services,
  }});

  final AppServices services;

  @override
  Widget build(BuildContext context) {{
    return MaterialApp(
      title: services.config.appName,
      theme: buildAppTheme(),
      home: _UpgradeGate(
        upgradeDecision: services.upgradeDecision,
        child: const HomePage(),
      ),
    );
  }}
}}

class _UpgradeGate extends StatefulWidget {{
  const _UpgradeGate({{
    required this.upgradeDecision,
    required this.child,
  }});

  final UpgradeDecision upgradeDecision;
  final Widget child;

  @override
  State<_UpgradeGate> createState() => _UpgradeGateState();
}}

class _UpgradeGateState extends State<_UpgradeGate> {{
  bool _dialogShown = false;

  @override
  void didChangeDependencies() {{
    super.didChangeDependencies();
    if (_dialogShown || !widget.upgradeDecision.shouldPrompt) {{
      return;
    }}

    _dialogShown = true;
    WidgetsBinding.instance.addPostFrameCallback((_) {{
      if (!mounted) {{
        return;
      }}

      showDialog<void>(
        context: context,
        barrierDismissible: !widget.upgradeDecision.isForced,
        builder: (BuildContext context) {{
          return AlertDialog(
            title: Text(widget.upgradeDecision.isForced ? 'Upgrade Required' : 'Update Available'),
            content: Text(
              widget.upgradeDecision.isForced
                  ? 'Your app version is too old. Please upgrade now to continue using the app.'
                  : 'A newer app version is available. Upgrade now for the latest fixes and features.',
            ),
            actions: <Widget>[
              if (!widget.upgradeDecision.isForced)
                TextButton(
                  onPressed: () => Navigator.of(context).pop(),
                  child: const Text('Later'),
                ),
              FilledButton(
                onPressed: () {{
                  Navigator.of(context).pop();
                  if (widget.upgradeDecision.isForced) {{
                    SystemNavigator.pop();
                  }}
                }},
                child: Text(widget.upgradeDecision.isForced ? 'Exit and Upgrade' : 'Upgrade'),
              ),
            ],
          );
        }},
      );
    }});
  }}

  @override
  Widget build(BuildContext context) {{
    return widget.child;
  }}
}}
"""


def build_main(package_name: str, class_name: str) -> str:
  return f"""import 'package:{package_name}/app/app.dart';
import 'package:{package_name}/app/bootstrap.dart';
import 'package:flutter/material.dart';

Future<void> main() async {{
  WidgetsFlutterBinding.ensureInitialized();
  final AppServices services = await bootstrapApp();
  runApp({class_name}(services: services));
}}
"""


def build_home_page(home_title: str) -> str:
  return f"""import 'package:flutter/material.dart';

class HomePage extends StatelessWidget {{
  const HomePage({{super.key}});

  @override
  Widget build(BuildContext context) {{
    return const Scaffold(
      body: Center(
        child: Text('{home_title}'),
      ),
    );
  }}
}}
"""


def build_bootstrap_test(package_name: str, app_name: str) -> str:
  return f"""import 'package:{package_name}/app/bootstrap.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {{
  test('bootstrap returns app services', () async {{
    final AppServices services = await bootstrapApp();

    expect(services.registry, isNotNull);
    expect(services.config.appName, '{app_name}');
    expect(services.upgradeDecision.shouldPrompt, isFalse);
  }});
}}
"""


def build_app_smoke_test(package_name: str, class_name: str, home_title: str) -> str:
  return f"""import 'package:{package_name}/app/app.dart';
import 'package:{package_name}/app/bootstrap.dart';
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {{
  testWidgets('renders product app shell', (WidgetTester tester) async {{
    final AppServices services = await bootstrapApp();

    await tester.pumpWidget({class_name}(services: services));

    expect(find.byType(MaterialApp), findsOneWidget);
    expect(find.text('{home_title}'), findsOneWidget);
  }});
}}
"""


def build_capability_registry_test() -> str:
  return """import 'package:app_factory_foundation/app_factory_foundation.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  test('registers and resolves capabilities by type', () {
    final CapabilityRegistry registry = CapabilityRegistry();

    registry.register<String>('logger');

    expect(registry.resolve<String>(), 'logger');
  });
}
"""


def build_class_name(app_name: str) -> str:
  words = ''.join(char if char.isalnum() else ' ' for char in app_name).split()
  return ''.join(word.capitalize() for word in words) + 'App'


def create_product_scaffold(repo_root: Path, product_slug: str, app_name: str) -> Path:
  product_root = repo_root / 'products' / product_slug
  if product_root.exists():
    raise FileExistsError(f'Product already exists: {product_root}')

  package_name = slug_to_package_name(product_slug)
  class_name = build_class_name(app_name)
  home_title = f'{app_name} Home'

  for relative in (
    'client/lib/app',
    'client/lib/features/home',
    'client/lib/integrations',
    'client/test/unit',
    'client/test/widget',
    'client/test/integration',
    'client/config/env',
    'client/assets',
    'server/src',
    'server/include',
    'server/tests',
    'server/config',
    'server/deploy',
    'build/outputs',
    'design/exports',
  ):
    (product_root / relative).mkdir(parents=True, exist_ok=True)

  write_text(product_root / 'client/pubspec.yaml', build_pubspec(app_name, product_slug))
  write_text(product_root / 'client/config/app.yaml', build_app_config(product_slug))
  write_text(product_root / 'client/config/env/dev.yaml', 'flavor: dev\nlogging: verbose\n')
  write_text(product_root / 'client/assets/.gitkeep', '')
  write_text(product_root / 'build/outputs/.gitkeep', '')
  write_text(product_root / 'client/lib/app/bootstrap.dart', build_bootstrap(app_name))
  write_text(product_root / 'client/lib/app/app.dart', build_app(package_name, class_name, home_title))
  write_text(product_root / 'client/lib/main.dart', build_main(package_name, class_name))
  write_text(product_root / 'client/lib/features/home/home_page.dart', build_home_page(home_title))
  write_text(product_root / 'client/test/unit/bootstrap_test.dart', build_bootstrap_test(package_name, app_name))
  write_text(product_root / 'client/test/unit/capability_registry_test.dart', build_capability_registry_test())
  write_text(product_root / 'client/test/widget/app_smoke_test.dart', build_app_smoke_test(package_name, class_name, home_title))
  write_text(product_root / 'server/README.md', build_server_readme(app_name))
  write_text(product_root / 'server/config/server.yaml', build_server_config(product_slug))
  write_text(product_root / 'server/src/.gitkeep', '')
  write_text(product_root / 'server/include/.gitkeep', '')
  write_text(product_root / 'server/tests/.gitkeep', '')
  write_text(product_root / 'server/deploy/.gitkeep', '')

  copy_doc_templates(repo_root, product_root, app_name, product_slug)
  return product_root


def main() -> None:
  parser = argparse.ArgumentParser(description='Initialize a new AppFactory product scaffold.')
  parser.add_argument('product_slug')
  parser.add_argument('app_name')
  args = parser.parse_args()

  repo_root = Path(__file__).resolve().parent.parent
  product_root = create_product_scaffold(repo_root, args.product_slug, args.app_name)
  print(f'Created product scaffold at {product_root}')


if __name__ == '__main__':
  main()
